name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: out
          path: out
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@main
        with: 
          name: out
          path: out
      - name: Sync files to hosting
        uses: sebastianpopp/ftp-action@releases/v2
        with: 
          host: www.delta-www.cz
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          remoteDir: web
          localDir: out
          forceSsl: true
          options: "--delete --asci"